# ============================================================
# PersistentVolumeClaim - Demande de stockage par l'application
# Auteur: KHLIFI HOUCEM / FORMATEUR DEVSECOPS & CLOUD
# ============================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-pvc
  namespace: demo-app
  labels:
    app: k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-storage
  resources:
    requests:
      storage: 1Gi
